// Automatically generated by "generate-oscap-datapoint-extractor-from-schema.py", do not edit!
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "oval_definitions.h"
#include "oval_external_probe.h"
#include "oval_types.h"
#include "oscap-tool.h"
#include <string.h>

#ifdef EXTERNAL_PROBE_COLLECT

typedef oval_external_probe_value_map_t *(*datapoint_generator_func)(const char *id);
typedef struct datapoint_generator {
    const char*              probe_type_str;
    datapoint_generator_func gen_func;
} datapoint_generator_t;


static oval_external_probe_value_t *generate_oval_sc_EntityItemBoolType(const char *id, const char *field) {
    return oval_external_probe_value_new_boolean(true);
}
    

static oval_external_probe_value_t *generate_oval_sc_EntityItemIntType(const char *id, const char *field) {
    return oval_external_probe_value_new_integer(1234567);
}
    

static oval_external_probe_value_t *generate_oval_sc_EntityItemIPAddressStringType(const char *id, const char *field) {
    return oval_external_probe_value_new_string("9.8.7.6");
}
    

static oval_external_probe_value_t *generate_oval_sc_EntityItemStringType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_oval_sc_EntityItemVersionType(const char *id, const char *field) {
    return oval_external_probe_value_new_string("9.8.7.6");
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemAddrTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemAdstypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemAuditType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemCmdletVerbType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemDriveTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemFileAttributeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemFileTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemGUIDType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemInterfaceTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemNamingContextType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemNTUserAccountTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemPeSubsystemType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemPeTargetMachineType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemProtocolType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemRegistryHiveType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemRegistryTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemServiceControlsAcceptedType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemServiceCurrentStateType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemServiceStartTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemServiceTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemSharedResourceTypeType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemSystemMetricIndexType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemUserRightType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    

static oval_external_probe_value_t *generate_win_sc_EntityItemWindowsViewType(const char *id, const char *field) {
    return oval_external_probe_value_new_stringf("${%s#%s}", id, field);
}
    
static oval_external_probe_value_map_t *generate_accesstoken_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "security_principle", generate_oval_sc_EntityItemStringType(id, "security_principle"),
        "seassignprimarytokenprivilege", generate_oval_sc_EntityItemBoolType(id, "seassignprimarytokenprivilege"),
        "seauditprivilege", generate_oval_sc_EntityItemBoolType(id, "seauditprivilege"),
        "sebackupprivilege", generate_oval_sc_EntityItemBoolType(id, "sebackupprivilege"),
        "sechangenotifyprivilege", generate_oval_sc_EntityItemBoolType(id, "sechangenotifyprivilege"),
        "secreateglobalprivilege", generate_oval_sc_EntityItemBoolType(id, "secreateglobalprivilege"),
        "secreatepagefileprivilege", generate_oval_sc_EntityItemBoolType(id, "secreatepagefileprivilege"),
        "secreatepermanentprivilege", generate_oval_sc_EntityItemBoolType(id, "secreatepermanentprivilege"),
        "secreatesymboliclinkprivilege", generate_oval_sc_EntityItemBoolType(id, "secreatesymboliclinkprivilege"),
        "secreatetokenprivilege", generate_oval_sc_EntityItemBoolType(id, "secreatetokenprivilege"),
        "sedebugprivilege", generate_oval_sc_EntityItemBoolType(id, "sedebugprivilege"),
        "seenabledelegationprivilege", generate_oval_sc_EntityItemBoolType(id, "seenabledelegationprivilege"),
        "seimpersonateprivilege", generate_oval_sc_EntityItemBoolType(id, "seimpersonateprivilege"),
        "seincreasebasepriorityprivilege", generate_oval_sc_EntityItemBoolType(id, "seincreasebasepriorityprivilege"),
        "seincreasequotaprivilege", generate_oval_sc_EntityItemBoolType(id, "seincreasequotaprivilege"),
        "seincreaseworkingsetprivilege", generate_oval_sc_EntityItemBoolType(id, "seincreaseworkingsetprivilege"),
        "seloaddriverprivilege", generate_oval_sc_EntityItemBoolType(id, "seloaddriverprivilege"),
        "selockmemoryprivilege", generate_oval_sc_EntityItemBoolType(id, "selockmemoryprivilege"),
        "semachineaccountprivilege", generate_oval_sc_EntityItemBoolType(id, "semachineaccountprivilege"),
        "semanagevolumeprivilege", generate_oval_sc_EntityItemBoolType(id, "semanagevolumeprivilege"),
        "seprofilesingleprocessprivilege", generate_oval_sc_EntityItemBoolType(id, "seprofilesingleprocessprivilege"),
        "serelabelprivilege", generate_oval_sc_EntityItemBoolType(id, "serelabelprivilege"),
        "seremoteshutdownprivilege", generate_oval_sc_EntityItemBoolType(id, "seremoteshutdownprivilege"),
        "serestoreprivilege", generate_oval_sc_EntityItemBoolType(id, "serestoreprivilege"),
        "sesecurityprivilege", generate_oval_sc_EntityItemBoolType(id, "sesecurityprivilege"),
        "seshutdownprivilege", generate_oval_sc_EntityItemBoolType(id, "seshutdownprivilege"),
        "sesyncagentprivilege", generate_oval_sc_EntityItemBoolType(id, "sesyncagentprivilege"),
        "sesystemenvironmentprivilege", generate_oval_sc_EntityItemBoolType(id, "sesystemenvironmentprivilege"),
        "sesystemprofileprivilege", generate_oval_sc_EntityItemBoolType(id, "sesystemprofileprivilege"),
        "sesystemtimeprivilege", generate_oval_sc_EntityItemBoolType(id, "sesystemtimeprivilege"),
        "setakeownershipprivilege", generate_oval_sc_EntityItemBoolType(id, "setakeownershipprivilege"),
        "setcbprivilege", generate_oval_sc_EntityItemBoolType(id, "setcbprivilege"),
        "setimezoneprivilege", generate_oval_sc_EntityItemBoolType(id, "setimezoneprivilege"),
        "seundockprivilege", generate_oval_sc_EntityItemBoolType(id, "seundockprivilege"),
        "seunsolicitedinputprivilege", generate_oval_sc_EntityItemBoolType(id, "seunsolicitedinputprivilege"),
        "sebatchlogonright", generate_oval_sc_EntityItemBoolType(id, "sebatchlogonright"),
        "seinteractivelogonright", generate_oval_sc_EntityItemBoolType(id, "seinteractivelogonright"),
        "senetworklogonright", generate_oval_sc_EntityItemBoolType(id, "senetworklogonright"),
        "seremoteinteractivelogonright", generate_oval_sc_EntityItemBoolType(id, "seremoteinteractivelogonright"),
        "seservicelogonright", generate_oval_sc_EntityItemBoolType(id, "seservicelogonright"),
        "sedenybatchLogonright", generate_oval_sc_EntityItemBoolType(id, "sedenybatchLogonright"),
        "sedenyinteractivelogonright", generate_oval_sc_EntityItemBoolType(id, "sedenyinteractivelogonright"),
        "sedenynetworklogonright", generate_oval_sc_EntityItemBoolType(id, "sedenynetworklogonright"),
        "sedenyremoteInteractivelogonright", generate_oval_sc_EntityItemBoolType(id, "sedenyremoteInteractivelogonright"),
        "sedenyservicelogonright", generate_oval_sc_EntityItemBoolType(id, "sedenyservicelogonright"),
        "setrustedcredmanaccessnameright", generate_oval_sc_EntityItemBoolType(id, "setrustedcredmanaccessnameright"),
        NULL);
}
static oval_external_probe_value_map_t *generate_activedirectory_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "naming_context", generate_win_sc_EntityItemNamingContextType(id, "naming_context"),
        "relative_dn", generate_oval_sc_EntityItemStringType(id, "relative_dn"),
        "attribute", generate_oval_sc_EntityItemStringType(id, "attribute"),
        "object_class", generate_oval_sc_EntityItemStringType(id, "object_class"),
        "adstype", generate_win_sc_EntityItemAdstypeType(id, "adstype"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_activedirectory57_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "naming_context", generate_win_sc_EntityItemNamingContextType(id, "naming_context"),
        "relative_dn", generate_oval_sc_EntityItemStringType(id, "relative_dn"),
        "attribute", generate_oval_sc_EntityItemStringType(id, "attribute"),
        "object_class", generate_oval_sc_EntityItemStringType(id, "object_class"),
        "adstype", generate_win_sc_EntityItemAdstypeType(id, "adstype"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_auditeventpolicy_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "account_logon", generate_win_sc_EntityItemAuditType(id, "account_logon"),
        "account_management", generate_win_sc_EntityItemAuditType(id, "account_management"),
        "detailed_tracking", generate_win_sc_EntityItemAuditType(id, "detailed_tracking"),
        "directory_service_access", generate_win_sc_EntityItemAuditType(id, "directory_service_access"),
        "logon", generate_win_sc_EntityItemAuditType(id, "logon"),
        "object_access", generate_win_sc_EntityItemAuditType(id, "object_access"),
        "policy_change", generate_win_sc_EntityItemAuditType(id, "policy_change"),
        "privilege_use", generate_win_sc_EntityItemAuditType(id, "privilege_use"),
        "system", generate_win_sc_EntityItemAuditType(id, "system"),
        NULL);
}
static oval_external_probe_value_map_t *generate_auditeventpolicysubcategories_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "credential_validation", generate_win_sc_EntityItemAuditType(id, "credential_validation"),
        "kerberos_authentication_service", generate_win_sc_EntityItemAuditType(id, "kerberos_authentication_service"),
        "kerberos_service_ticket_operations", generate_win_sc_EntityItemAuditType(id, "kerberos_service_ticket_operations"),
        "kerberos_ticket_events", generate_win_sc_EntityItemAuditType(id, "kerberos_ticket_events"),
        "other_account_logon_events", generate_win_sc_EntityItemAuditType(id, "other_account_logon_events"),
        "application_group_management", generate_win_sc_EntityItemAuditType(id, "application_group_management"),
        "computer_account_management", generate_win_sc_EntityItemAuditType(id, "computer_account_management"),
        "distribution_group_management", generate_win_sc_EntityItemAuditType(id, "distribution_group_management"),
        "other_account_management_events", generate_win_sc_EntityItemAuditType(id, "other_account_management_events"),
        "security_group_management", generate_win_sc_EntityItemAuditType(id, "security_group_management"),
        "user_account_management", generate_win_sc_EntityItemAuditType(id, "user_account_management"),
        "dpapi_activity", generate_win_sc_EntityItemAuditType(id, "dpapi_activity"),
        "process_creation", generate_win_sc_EntityItemAuditType(id, "process_creation"),
        "process_termination", generate_win_sc_EntityItemAuditType(id, "process_termination"),
        "rpc_events", generate_win_sc_EntityItemAuditType(id, "rpc_events"),
        "directory_service_access", generate_win_sc_EntityItemAuditType(id, "directory_service_access"),
        "directory_service_changes", generate_win_sc_EntityItemAuditType(id, "directory_service_changes"),
        "directory_service_replication", generate_win_sc_EntityItemAuditType(id, "directory_service_replication"),
        "detailed_directory_service_replication", generate_win_sc_EntityItemAuditType(id, "detailed_directory_service_replication"),
        "account_lockout", generate_win_sc_EntityItemAuditType(id, "account_lockout"),
        "ipsec_extended_mode", generate_win_sc_EntityItemAuditType(id, "ipsec_extended_mode"),
        "ipsec_main_mode", generate_win_sc_EntityItemAuditType(id, "ipsec_main_mode"),
        "ipsec_quick_mode", generate_win_sc_EntityItemAuditType(id, "ipsec_quick_mode"),
        "logoff", generate_win_sc_EntityItemAuditType(id, "logoff"),
        "logon", generate_win_sc_EntityItemAuditType(id, "logon"),
        "network_policy_server", generate_win_sc_EntityItemAuditType(id, "network_policy_server"),
        "other_logon_logoff_events", generate_win_sc_EntityItemAuditType(id, "other_logon_logoff_events"),
        "special_logon", generate_win_sc_EntityItemAuditType(id, "special_logon"),
        "logon_claims", generate_win_sc_EntityItemAuditType(id, "logon_claims"),
        "application_generated", generate_win_sc_EntityItemAuditType(id, "application_generated"),
        "certification_services", generate_win_sc_EntityItemAuditType(id, "certification_services"),
        "detailed_file_share", generate_win_sc_EntityItemAuditType(id, "detailed_file_share"),
        "file_share", generate_win_sc_EntityItemAuditType(id, "file_share"),
        "file_system", generate_win_sc_EntityItemAuditType(id, "file_system"),
        "filtering_platform_connection", generate_win_sc_EntityItemAuditType(id, "filtering_platform_connection"),
        "filtering_platform_packet_drop", generate_win_sc_EntityItemAuditType(id, "filtering_platform_packet_drop"),
        "handle_manipulation", generate_win_sc_EntityItemAuditType(id, "handle_manipulation"),
        "kernel_object", generate_win_sc_EntityItemAuditType(id, "kernel_object"),
        "other_object_access_events", generate_win_sc_EntityItemAuditType(id, "other_object_access_events"),
        "registry", generate_win_sc_EntityItemAuditType(id, "registry"),
        "sam", generate_win_sc_EntityItemAuditType(id, "sam"),
        "removable_storage", generate_win_sc_EntityItemAuditType(id, "removable_storage"),
        "central_access_policy_staging", generate_win_sc_EntityItemAuditType(id, "central_access_policy_staging"),
        "audit_policy_change", generate_win_sc_EntityItemAuditType(id, "audit_policy_change"),
        "authentication_policy_change", generate_win_sc_EntityItemAuditType(id, "authentication_policy_change"),
        "authorization_policy_change", generate_win_sc_EntityItemAuditType(id, "authorization_policy_change"),
        "filtering_platform_policy_change", generate_win_sc_EntityItemAuditType(id, "filtering_platform_policy_change"),
        "mpssvc_rule_level_policy_change", generate_win_sc_EntityItemAuditType(id, "mpssvc_rule_level_policy_change"),
        "other_policy_change_events", generate_win_sc_EntityItemAuditType(id, "other_policy_change_events"),
        "non_sensitive_privilege_use", generate_win_sc_EntityItemAuditType(id, "non_sensitive_privilege_use"),
        "other_privilege_use_events", generate_win_sc_EntityItemAuditType(id, "other_privilege_use_events"),
        "sensitive_privilege_use", generate_win_sc_EntityItemAuditType(id, "sensitive_privilege_use"),
        "ipsec_driver", generate_win_sc_EntityItemAuditType(id, "ipsec_driver"),
        "other_system_events", generate_win_sc_EntityItemAuditType(id, "other_system_events"),
        "security_state_change", generate_win_sc_EntityItemAuditType(id, "security_state_change"),
        "security_system_extension", generate_win_sc_EntityItemAuditType(id, "security_system_extension"),
        "system_integrity", generate_win_sc_EntityItemAuditType(id, "system_integrity"),
        "group_membership", generate_win_sc_EntityItemAuditType(id, "group_membership"),
        "pnp_activity", generate_win_sc_EntityItemAuditType(id, "pnp_activity"),
        "user_device_claims", generate_win_sc_EntityItemAuditType(id, "user_device_claims"),
        "audit_detailedtracking_tokenrightadjusted", generate_win_sc_EntityItemAuditType(id, "audit_detailedtracking_tokenrightadjusted"),
        NULL);
}
static oval_external_probe_value_map_t *generate_cmdlet_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "module_name", generate_oval_sc_EntityItemStringType(id, "module_name"),
        "module_id", generate_win_sc_EntityItemGUIDType(id, "module_id"),
        "module_version", generate_oval_sc_EntityItemVersionType(id, "module_version"),
        "verb", generate_win_sc_EntityItemCmdletVerbType(id, "verb"),
        "noun", generate_oval_sc_EntityItemStringType(id, "noun"),
        "parameters", generate_oval_sc_EntityItemStringType(id, "parameters"),
        "select", generate_oval_sc_EntityItemStringType(id, "select"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_dnscache_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "domain_name", generate_oval_sc_EntityItemStringType(id, "domain_name"),
        "ttl", generate_oval_sc_EntityItemIntType(id, "ttl"),
        "ip_address", generate_oval_sc_EntityItemIPAddressStringType(id, "ip_address"),
        NULL);
}
static oval_external_probe_value_map_t *generate_file_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "filepath", generate_oval_sc_EntityItemStringType(id, "filepath"),
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "filename", generate_oval_sc_EntityItemStringType(id, "filename"),
        "owner", generate_oval_sc_EntityItemStringType(id, "owner"),
        "size", generate_oval_sc_EntityItemIntType(id, "size"),
        "a_time", generate_oval_sc_EntityItemIntType(id, "a_time"),
        "c_time", generate_oval_sc_EntityItemIntType(id, "c_time"),
        "m_time", generate_oval_sc_EntityItemIntType(id, "m_time"),
        "ms_checksum", generate_oval_sc_EntityItemStringType(id, "ms_checksum"),
        "version", generate_oval_sc_EntityItemVersionType(id, "version"),
        "type", generate_win_sc_EntityItemFileTypeType(id, "type"),
        "attribute", generate_win_sc_EntityItemFileAttributeType(id, "attribute"),
        "development_class", generate_oval_sc_EntityItemStringType(id, "development_class"),
        "company", generate_oval_sc_EntityItemStringType(id, "company"),
        "internal_name", generate_oval_sc_EntityItemStringType(id, "internal_name"),
        "language", generate_oval_sc_EntityItemStringType(id, "language"),
        "original_filename", generate_oval_sc_EntityItemStringType(id, "original_filename"),
        "product_name", generate_oval_sc_EntityItemStringType(id, "product_name"),
        "product_version", generate_oval_sc_EntityItemIntType(id, "product_version"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_fileauditedpermissions_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "filepath", generate_oval_sc_EntityItemStringType(id, "filepath"),
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "filename", generate_oval_sc_EntityItemStringType(id, "filename"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "standard_delete", generate_win_sc_EntityItemAuditType(id, "standard_delete"),
        "standard_read_control", generate_win_sc_EntityItemAuditType(id, "standard_read_control"),
        "standard_write_dac", generate_win_sc_EntityItemAuditType(id, "standard_write_dac"),
        "standard_write_owner", generate_win_sc_EntityItemAuditType(id, "standard_write_owner"),
        "standard_synchronize", generate_win_sc_EntityItemAuditType(id, "standard_synchronize"),
        "access_system_security", generate_win_sc_EntityItemAuditType(id, "access_system_security"),
        "generic_read", generate_win_sc_EntityItemAuditType(id, "generic_read"),
        "generic_write", generate_win_sc_EntityItemAuditType(id, "generic_write"),
        "generic_execute", generate_win_sc_EntityItemAuditType(id, "generic_execute"),
        "generic_all", generate_win_sc_EntityItemAuditType(id, "generic_all"),
        "file_read_data", generate_win_sc_EntityItemAuditType(id, "file_read_data"),
        "file_write_data", generate_win_sc_EntityItemAuditType(id, "file_write_data"),
        "file_append_data", generate_win_sc_EntityItemAuditType(id, "file_append_data"),
        "file_read_ea", generate_win_sc_EntityItemAuditType(id, "file_read_ea"),
        "file_write_ea", generate_win_sc_EntityItemAuditType(id, "file_write_ea"),
        "file_execute", generate_win_sc_EntityItemAuditType(id, "file_execute"),
        "file_delete_child", generate_win_sc_EntityItemAuditType(id, "file_delete_child"),
        "file_read_attributes", generate_win_sc_EntityItemAuditType(id, "file_read_attributes"),
        "file_write_attributes", generate_win_sc_EntityItemAuditType(id, "file_write_attributes"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_fileeffectiverights_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "filepath", generate_oval_sc_EntityItemStringType(id, "filepath"),
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "filename", generate_oval_sc_EntityItemStringType(id, "filename"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "standard_delete", generate_oval_sc_EntityItemBoolType(id, "standard_delete"),
        "standard_read_control", generate_oval_sc_EntityItemBoolType(id, "standard_read_control"),
        "standard_write_dac", generate_oval_sc_EntityItemBoolType(id, "standard_write_dac"),
        "standard_write_owner", generate_oval_sc_EntityItemBoolType(id, "standard_write_owner"),
        "standard_synchronize", generate_oval_sc_EntityItemBoolType(id, "standard_synchronize"),
        "access_system_security", generate_oval_sc_EntityItemBoolType(id, "access_system_security"),
        "generic_read", generate_oval_sc_EntityItemBoolType(id, "generic_read"),
        "generic_write", generate_oval_sc_EntityItemBoolType(id, "generic_write"),
        "generic_execute", generate_oval_sc_EntityItemBoolType(id, "generic_execute"),
        "generic_all", generate_oval_sc_EntityItemBoolType(id, "generic_all"),
        "file_read_data", generate_oval_sc_EntityItemBoolType(id, "file_read_data"),
        "file_write_data", generate_oval_sc_EntityItemBoolType(id, "file_write_data"),
        "file_append_data", generate_oval_sc_EntityItemBoolType(id, "file_append_data"),
        "file_read_ea", generate_oval_sc_EntityItemBoolType(id, "file_read_ea"),
        "file_write_ea", generate_oval_sc_EntityItemBoolType(id, "file_write_ea"),
        "file_execute", generate_oval_sc_EntityItemBoolType(id, "file_execute"),
        "file_delete_child", generate_oval_sc_EntityItemBoolType(id, "file_delete_child"),
        "file_read_attributes", generate_oval_sc_EntityItemBoolType(id, "file_read_attributes"),
        "file_write_attributes", generate_oval_sc_EntityItemBoolType(id, "file_write_attributes"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_group_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "group", generate_oval_sc_EntityItemStringType(id, "group"),
        "user", generate_oval_sc_EntityItemStringType(id, "user"),
        "subgroup", generate_oval_sc_EntityItemStringType(id, "subgroup"),
        NULL);
}
static oval_external_probe_value_map_t *generate_group_sid_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "group_sid", generate_oval_sc_EntityItemStringType(id, "group_sid"),
        "user_sid", generate_oval_sc_EntityItemStringType(id, "user_sid"),
        "subgroup_sid", generate_oval_sc_EntityItemStringType(id, "subgroup_sid"),
        NULL);
}
static oval_external_probe_value_map_t *generate_interface_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "index", generate_oval_sc_EntityItemIntType(id, "index"),
        "type", generate_win_sc_EntityItemInterfaceTypeType(id, "type"),
        "hardware_addr", generate_oval_sc_EntityItemStringType(id, "hardware_addr"),
        "inet_addr", generate_oval_sc_EntityItemIPAddressStringType(id, "inet_addr"),
        "broadcast_addr", generate_oval_sc_EntityItemIPAddressStringType(id, "broadcast_addr"),
        "netmask", generate_oval_sc_EntityItemIPAddressStringType(id, "netmask"),
        "addr_type", generate_win_sc_EntityItemAddrTypeType(id, "addr_type"),
        NULL);
}
static oval_external_probe_value_map_t *generate_junction_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "canonical_path", generate_oval_sc_EntityItemStringType(id, "canonical_path"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_license_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "type", generate_win_sc_EntityItemRegistryTypeType(id, "type"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_lockoutpolicy_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "force_logoff", generate_oval_sc_EntityItemIntType(id, "force_logoff"),
        "lockout_duration", generate_oval_sc_EntityItemIntType(id, "lockout_duration"),
        "lockout_observation_window", generate_oval_sc_EntityItemIntType(id, "lockout_observation_window"),
        "lockout_threshold", generate_oval_sc_EntityItemIntType(id, "lockout_threshold"),
        NULL);
}
static oval_external_probe_value_map_t *generate_metabase_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "key", generate_oval_sc_EntityItemStringType(id, "key"),
        "id", generate_oval_sc_EntityItemIntType(id, "id"),
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "user_type", generate_oval_sc_EntityItemStringType(id, "user_type"),
        "data_type", generate_oval_sc_EntityItemStringType(id, "data_type"),
        "data", generate_oval_sc_EntityItemStringType(id, "data"),
        NULL);
}
static oval_external_probe_value_map_t *generate_ntuser_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "key", generate_oval_sc_EntityItemStringType(id, "key"),
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "sid", generate_oval_sc_EntityItemStringType(id, "sid"),
        "username", generate_oval_sc_EntityItemStringType(id, "username"),
        "account_type", generate_win_sc_EntityItemNTUserAccountTypeType(id, "account_type"),
        "logged_on", generate_oval_sc_EntityItemBoolType(id, "logged_on"),
        "enabled", generate_oval_sc_EntityItemBoolType(id, "enabled"),
        "date_modified", generate_oval_sc_EntityItemIntType(id, "date_modified"),
        "days_since_modified", generate_oval_sc_EntityItemIntType(id, "days_since_modified"),
        "filepath", generate_oval_sc_EntityItemStringType(id, "filepath"),
        "last_write_time", generate_oval_sc_EntityItemIntType(id, "last_write_time"),
        "type", generate_win_sc_EntityItemRegistryTypeType(id, "type"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_passwordpolicy_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "max_passwd_age", generate_oval_sc_EntityItemIntType(id, "max_passwd_age"),
        "min_passwd_age", generate_oval_sc_EntityItemIntType(id, "min_passwd_age"),
        "min_passwd_len", generate_oval_sc_EntityItemIntType(id, "min_passwd_len"),
        "password_hist_len", generate_oval_sc_EntityItemIntType(id, "password_hist_len"),
        "password_complexity", generate_oval_sc_EntityItemBoolType(id, "password_complexity"),
        "reversible_encryption", generate_oval_sc_EntityItemBoolType(id, "reversible_encryption"),
        "anonymous_name_lookup", generate_oval_sc_EntityItemBoolType(id, "anonymous_name_lookup"),
        NULL);
}
static oval_external_probe_value_map_t *generate_peheader_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "filepath", generate_oval_sc_EntityItemStringType(id, "filepath"),
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "filename", generate_oval_sc_EntityItemStringType(id, "filename"),
        "header_signature", generate_oval_sc_EntityItemStringType(id, "header_signature"),
        "target_machine_type", generate_win_sc_EntityItemPeTargetMachineType(id, "target_machine_type"),
        "number_of_sections", generate_oval_sc_EntityItemIntType(id, "number_of_sections"),
        "time_date_stamp", generate_oval_sc_EntityItemIntType(id, "time_date_stamp"),
        "pointer_to_symbol_table", generate_oval_sc_EntityItemIntType(id, "pointer_to_symbol_table"),
        "number_of_symbols", generate_oval_sc_EntityItemIntType(id, "number_of_symbols"),
        "size_of_optional_header", generate_oval_sc_EntityItemIntType(id, "size_of_optional_header"),
        "image_file_relocs_stripped", generate_oval_sc_EntityItemBoolType(id, "image_file_relocs_stripped"),
        "image_file_executable_image", generate_oval_sc_EntityItemBoolType(id, "image_file_executable_image"),
        "image_file_line_nums_stripped", generate_oval_sc_EntityItemBoolType(id, "image_file_line_nums_stripped"),
        "image_file_local_syms_stripped", generate_oval_sc_EntityItemBoolType(id, "image_file_local_syms_stripped"),
        "image_file_aggresive_ws_trim", generate_oval_sc_EntityItemBoolType(id, "image_file_aggresive_ws_trim"),
        "image_file_large_address_aware", generate_oval_sc_EntityItemBoolType(id, "image_file_large_address_aware"),
        "image_file_16bit_machine", generate_oval_sc_EntityItemBoolType(id, "image_file_16bit_machine"),
        "image_file_bytes_reversed_lo", generate_oval_sc_EntityItemBoolType(id, "image_file_bytes_reversed_lo"),
        "image_file_32bit_machine", generate_oval_sc_EntityItemBoolType(id, "image_file_32bit_machine"),
        "image_file_debug_stripped", generate_oval_sc_EntityItemBoolType(id, "image_file_debug_stripped"),
        "image_file_removable_run_from_swap", generate_oval_sc_EntityItemBoolType(id, "image_file_removable_run_from_swap"),
        "image_file_system", generate_oval_sc_EntityItemBoolType(id, "image_file_system"),
        "image_file_dll", generate_oval_sc_EntityItemBoolType(id, "image_file_dll"),
        "image_file_up_system_only", generate_oval_sc_EntityItemBoolType(id, "image_file_up_system_only"),
        "image_file_bytes_reveresed_hi", generate_oval_sc_EntityItemBoolType(id, "image_file_bytes_reveresed_hi"),
        "magic_number", generate_oval_sc_EntityItemIntType(id, "magic_number"),
        "major_linker_version", generate_oval_sc_EntityItemIntType(id, "major_linker_version"),
        "minor_linker_version", generate_oval_sc_EntityItemIntType(id, "minor_linker_version"),
        "size_of_code", generate_oval_sc_EntityItemIntType(id, "size_of_code"),
        "size_of_initialized_data", generate_oval_sc_EntityItemIntType(id, "size_of_initialized_data"),
        "size_of_uninitialized_data", generate_oval_sc_EntityItemIntType(id, "size_of_uninitialized_data"),
        "address_of_entry_point", generate_oval_sc_EntityItemIntType(id, "address_of_entry_point"),
        "base_of_code", generate_oval_sc_EntityItemIntType(id, "base_of_code"),
        "base_of_data", generate_oval_sc_EntityItemIntType(id, "base_of_data"),
        "image_base_address", generate_oval_sc_EntityItemIntType(id, "image_base_address"),
        "section_alignment", generate_oval_sc_EntityItemIntType(id, "section_alignment"),
        "file_alignment", generate_oval_sc_EntityItemIntType(id, "file_alignment"),
        "major_operating_system_version", generate_oval_sc_EntityItemIntType(id, "major_operating_system_version"),
        "minor_operating_system_version", generate_oval_sc_EntityItemIntType(id, "minor_operating_system_version"),
        "major_image_version", generate_oval_sc_EntityItemIntType(id, "major_image_version"),
        "minor_image_version", generate_oval_sc_EntityItemIntType(id, "minor_image_version"),
        "major_subsystem_version", generate_oval_sc_EntityItemIntType(id, "major_subsystem_version"),
        "minor_susbsystem_version", generate_oval_sc_EntityItemIntType(id, "minor_susbsystem_version"),
        "size_of_image", generate_oval_sc_EntityItemIntType(id, "size_of_image"),
        "size_of_headers", generate_oval_sc_EntityItemIntType(id, "size_of_headers"),
        "checksum", generate_oval_sc_EntityItemIntType(id, "checksum"),
        "subsystem", generate_win_sc_EntityItemPeSubsystemType(id, "subsystem"),
        "dll_characteristics", generate_oval_sc_EntityItemIntType(id, "dll_characteristics"),
        "size_of_stack_reserve", generate_oval_sc_EntityItemIntType(id, "size_of_stack_reserve"),
        "size_of_stack_commit", generate_oval_sc_EntityItemIntType(id, "size_of_stack_commit"),
        "size_of_heap_reserve", generate_oval_sc_EntityItemIntType(id, "size_of_heap_reserve"),
        "size_of_heap_commit", generate_oval_sc_EntityItemIntType(id, "size_of_heap_commit"),
        "loader_flags", generate_oval_sc_EntityItemIntType(id, "loader_flags"),
        "number_of_rva_and_sizes", generate_oval_sc_EntityItemIntType(id, "number_of_rva_and_sizes"),
        "real_number_of_directory_entries", generate_oval_sc_EntityItemIntType(id, "real_number_of_directory_entries"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_port_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "local_address", generate_oval_sc_EntityItemIPAddressStringType(id, "local_address"),
        "local_port", generate_oval_sc_EntityItemIntType(id, "local_port"),
        "protocol", generate_win_sc_EntityItemProtocolType(id, "protocol"),
        "pid", generate_oval_sc_EntityItemIntType(id, "pid"),
        "foreign_address", generate_oval_sc_EntityItemIPAddressStringType(id, "foreign_address"),
        "foreign_port", generate_oval_sc_EntityItemStringType(id, "foreign_port"),
        NULL);
}
static oval_external_probe_value_map_t *generate_printereffectiverights_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "printer_name", generate_oval_sc_EntityItemStringType(id, "printer_name"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "standard_delete", generate_oval_sc_EntityItemBoolType(id, "standard_delete"),
        "standard_read_control", generate_oval_sc_EntityItemBoolType(id, "standard_read_control"),
        "standard_write_dac", generate_oval_sc_EntityItemBoolType(id, "standard_write_dac"),
        "standard_write_owner", generate_oval_sc_EntityItemBoolType(id, "standard_write_owner"),
        "standard_synchronize", generate_oval_sc_EntityItemBoolType(id, "standard_synchronize"),
        "access_system_security", generate_oval_sc_EntityItemBoolType(id, "access_system_security"),
        "generic_read", generate_oval_sc_EntityItemBoolType(id, "generic_read"),
        "generic_write", generate_oval_sc_EntityItemBoolType(id, "generic_write"),
        "generic_execute", generate_oval_sc_EntityItemBoolType(id, "generic_execute"),
        "generic_all", generate_oval_sc_EntityItemBoolType(id, "generic_all"),
        "printer_access_administer", generate_oval_sc_EntityItemBoolType(id, "printer_access_administer"),
        "printer_access_use", generate_oval_sc_EntityItemBoolType(id, "printer_access_use"),
        "job_access_administer", generate_oval_sc_EntityItemBoolType(id, "job_access_administer"),
        "job_access_read", generate_oval_sc_EntityItemBoolType(id, "job_access_read"),
        NULL);
}
static oval_external_probe_value_map_t *generate_process_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "command_line", generate_oval_sc_EntityItemStringType(id, "command_line"),
        "pid", generate_oval_sc_EntityItemIntType(id, "pid"),
        "ppid", generate_oval_sc_EntityItemIntType(id, "ppid"),
        "priority", generate_oval_sc_EntityItemIntType(id, "priority"),
        "image_path", generate_oval_sc_EntityItemStringType(id, "image_path"),
        "current_dir", generate_oval_sc_EntityItemStringType(id, "current_dir"),
        "creation_time", generate_oval_sc_EntityItemIntType(id, "creation_time"),
        "dep_enabled", generate_oval_sc_EntityItemBoolType(id, "dep_enabled"),
        "primary_window_text", generate_oval_sc_EntityItemStringType(id, "primary_window_text"),
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        NULL);
}
static oval_external_probe_value_map_t *generate_registry_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "hive", generate_win_sc_EntityItemRegistryHiveType(id, "hive"),
        "key", generate_oval_sc_EntityItemStringType(id, "key"),
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "last_write_time", generate_oval_sc_EntityItemIntType(id, "last_write_time"),
        "type", generate_win_sc_EntityItemRegistryTypeType(id, "type"),
        "value", generate_oval_sc_EntityItemStringType(id, "value"),
        "expanded_value", generate_oval_sc_EntityItemStringType(id, "expanded_value"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_regkeyauditedpermissions_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "hive", generate_win_sc_EntityItemRegistryHiveType(id, "hive"),
        "key", generate_oval_sc_EntityItemStringType(id, "key"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "standard_delete", generate_win_sc_EntityItemAuditType(id, "standard_delete"),
        "standard_read_control", generate_win_sc_EntityItemAuditType(id, "standard_read_control"),
        "standard_write_dac", generate_win_sc_EntityItemAuditType(id, "standard_write_dac"),
        "standard_write_owner", generate_win_sc_EntityItemAuditType(id, "standard_write_owner"),
        "standard_synchronize", generate_win_sc_EntityItemAuditType(id, "standard_synchronize"),
        "access_system_security", generate_win_sc_EntityItemAuditType(id, "access_system_security"),
        "generic_read", generate_win_sc_EntityItemAuditType(id, "generic_read"),
        "generic_write", generate_win_sc_EntityItemAuditType(id, "generic_write"),
        "generic_execute", generate_win_sc_EntityItemAuditType(id, "generic_execute"),
        "generic_all", generate_win_sc_EntityItemAuditType(id, "generic_all"),
        "key_query_value", generate_win_sc_EntityItemAuditType(id, "key_query_value"),
        "key_set_value", generate_win_sc_EntityItemAuditType(id, "key_set_value"),
        "key_create_sub_key", generate_win_sc_EntityItemAuditType(id, "key_create_sub_key"),
        "key_enumerate_sub_keys", generate_win_sc_EntityItemAuditType(id, "key_enumerate_sub_keys"),
        "key_notify", generate_win_sc_EntityItemAuditType(id, "key_notify"),
        "key_create_link", generate_win_sc_EntityItemAuditType(id, "key_create_link"),
        "key_wow64_64key", generate_win_sc_EntityItemAuditType(id, "key_wow64_64key"),
        "key_wow64_32key", generate_win_sc_EntityItemAuditType(id, "key_wow64_32key"),
        "key_wow64_res", generate_win_sc_EntityItemAuditType(id, "key_wow64_res"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_regkeyeffectiverights_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "hive", generate_win_sc_EntityItemRegistryHiveType(id, "hive"),
        "key", generate_oval_sc_EntityItemStringType(id, "key"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "standard_delete", generate_oval_sc_EntityItemBoolType(id, "standard_delete"),
        "standard_read_control", generate_oval_sc_EntityItemBoolType(id, "standard_read_control"),
        "standard_write_dac", generate_oval_sc_EntityItemBoolType(id, "standard_write_dac"),
        "standard_write_owner", generate_oval_sc_EntityItemBoolType(id, "standard_write_owner"),
        "standard_synchronize", generate_oval_sc_EntityItemBoolType(id, "standard_synchronize"),
        "access_system_security", generate_oval_sc_EntityItemBoolType(id, "access_system_security"),
        "generic_read", generate_oval_sc_EntityItemBoolType(id, "generic_read"),
        "generic_write", generate_oval_sc_EntityItemBoolType(id, "generic_write"),
        "generic_execute", generate_oval_sc_EntityItemBoolType(id, "generic_execute"),
        "generic_all", generate_oval_sc_EntityItemBoolType(id, "generic_all"),
        "key_query_value", generate_oval_sc_EntityItemBoolType(id, "key_query_value"),
        "key_set_value", generate_oval_sc_EntityItemBoolType(id, "key_set_value"),
        "key_create_sub_key", generate_oval_sc_EntityItemBoolType(id, "key_create_sub_key"),
        "key_enumerate_sub_keys", generate_oval_sc_EntityItemBoolType(id, "key_enumerate_sub_keys"),
        "key_notify", generate_oval_sc_EntityItemBoolType(id, "key_notify"),
        "key_create_link", generate_oval_sc_EntityItemBoolType(id, "key_create_link"),
        "key_wow64_64key", generate_oval_sc_EntityItemBoolType(id, "key_wow64_64key"),
        "key_wow64_32key", generate_oval_sc_EntityItemBoolType(id, "key_wow64_32key"),
        "key_wow64_res", generate_oval_sc_EntityItemBoolType(id, "key_wow64_res"),
        "windows_view", generate_win_sc_EntityItemWindowsViewType(id, "windows_view"),
        NULL);
}
static oval_external_probe_value_map_t *generate_service_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "service_name", generate_oval_sc_EntityItemStringType(id, "service_name"),
        "display_name", generate_oval_sc_EntityItemStringType(id, "display_name"),
        "description", generate_oval_sc_EntityItemStringType(id, "description"),
        "service_type", generate_win_sc_EntityItemServiceTypeType(id, "service_type"),
        "start_type", generate_win_sc_EntityItemServiceStartTypeType(id, "start_type"),
        "current_state", generate_win_sc_EntityItemServiceCurrentStateType(id, "current_state"),
        "controls_accepted", generate_win_sc_EntityItemServiceControlsAcceptedType(id, "controls_accepted"),
        "start_name", generate_oval_sc_EntityItemStringType(id, "start_name"),
        "path", generate_oval_sc_EntityItemStringType(id, "path"),
        "pid", generate_oval_sc_EntityItemIntType(id, "pid"),
        "service_flag", generate_oval_sc_EntityItemBoolType(id, "service_flag"),
        "dependencies", generate_oval_sc_EntityItemStringType(id, "dependencies"),
        NULL);
}
static oval_external_probe_value_map_t *generate_serviceeffectiverights_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "service_name", generate_oval_sc_EntityItemStringType(id, "service_name"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "standard_delete", generate_oval_sc_EntityItemBoolType(id, "standard_delete"),
        "standard_read_control", generate_oval_sc_EntityItemBoolType(id, "standard_read_control"),
        "standard_write_dac", generate_oval_sc_EntityItemBoolType(id, "standard_write_dac"),
        "standard_write_owner", generate_oval_sc_EntityItemBoolType(id, "standard_write_owner"),
        "generic_read", generate_oval_sc_EntityItemBoolType(id, "generic_read"),
        "generic_write", generate_oval_sc_EntityItemBoolType(id, "generic_write"),
        "generic_execute", generate_oval_sc_EntityItemBoolType(id, "generic_execute"),
        "service_query_conf", generate_oval_sc_EntityItemBoolType(id, "service_query_conf"),
        "service_change_conf", generate_oval_sc_EntityItemBoolType(id, "service_change_conf"),
        "service_query_stat", generate_oval_sc_EntityItemBoolType(id, "service_query_stat"),
        "service_enum_dependents", generate_oval_sc_EntityItemBoolType(id, "service_enum_dependents"),
        "service_start", generate_oval_sc_EntityItemBoolType(id, "service_start"),
        "service_stop", generate_oval_sc_EntityItemBoolType(id, "service_stop"),
        "service_pause", generate_oval_sc_EntityItemBoolType(id, "service_pause"),
        "service_interrogate", generate_oval_sc_EntityItemBoolType(id, "service_interrogate"),
        "service_user_defined", generate_oval_sc_EntityItemBoolType(id, "service_user_defined"),
        NULL);
}
static oval_external_probe_value_map_t *generate_sharedresource_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "netname", generate_oval_sc_EntityItemStringType(id, "netname"),
        "shared_type", generate_win_sc_EntityItemSharedResourceTypeType(id, "shared_type"),
        "max_uses", generate_oval_sc_EntityItemIntType(id, "max_uses"),
        "current_uses", generate_oval_sc_EntityItemIntType(id, "current_uses"),
        "local_path", generate_oval_sc_EntityItemStringType(id, "local_path"),
        "access_read_permission", generate_oval_sc_EntityItemBoolType(id, "access_read_permission"),
        "access_write_permission", generate_oval_sc_EntityItemBoolType(id, "access_write_permission"),
        "access_create_permission", generate_oval_sc_EntityItemBoolType(id, "access_create_permission"),
        "access_exec_permission", generate_oval_sc_EntityItemBoolType(id, "access_exec_permission"),
        "access_delete_permission", generate_oval_sc_EntityItemBoolType(id, "access_delete_permission"),
        "access_atrib_permission", generate_oval_sc_EntityItemBoolType(id, "access_atrib_permission"),
        "access_perm_permission", generate_oval_sc_EntityItemBoolType(id, "access_perm_permission"),
        "access_all_permission", generate_oval_sc_EntityItemBoolType(id, "access_all_permission"),
        NULL);
}
static oval_external_probe_value_map_t *generate_sharedresourceauditedpermissions_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "netname", generate_oval_sc_EntityItemStringType(id, "netname"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "standard_delete", generate_win_sc_EntityItemAuditType(id, "standard_delete"),
        "standard_read_control", generate_win_sc_EntityItemAuditType(id, "standard_read_control"),
        "standard_write_dac", generate_win_sc_EntityItemAuditType(id, "standard_write_dac"),
        "standard_write_owner", generate_win_sc_EntityItemAuditType(id, "standard_write_owner"),
        "standard_synchronize", generate_win_sc_EntityItemAuditType(id, "standard_synchronize"),
        "access_system_security", generate_win_sc_EntityItemAuditType(id, "access_system_security"),
        "generic_read", generate_win_sc_EntityItemAuditType(id, "generic_read"),
        "generic_write", generate_win_sc_EntityItemAuditType(id, "generic_write"),
        "generic_execute", generate_win_sc_EntityItemAuditType(id, "generic_execute"),
        "generic_all", generate_win_sc_EntityItemAuditType(id, "generic_all"),
        NULL);
}
static oval_external_probe_value_map_t *generate_sharedresourceeffectiverights_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "netname", generate_oval_sc_EntityItemStringType(id, "netname"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "standard_delete", generate_oval_sc_EntityItemBoolType(id, "standard_delete"),
        "standard_read_control", generate_oval_sc_EntityItemBoolType(id, "standard_read_control"),
        "standard_write_dac", generate_oval_sc_EntityItemBoolType(id, "standard_write_dac"),
        "standard_write_owner", generate_oval_sc_EntityItemBoolType(id, "standard_write_owner"),
        "standard_synchronize", generate_oval_sc_EntityItemBoolType(id, "standard_synchronize"),
        "access_system_security", generate_oval_sc_EntityItemBoolType(id, "access_system_security"),
        "generic_read", generate_oval_sc_EntityItemBoolType(id, "generic_read"),
        "generic_write", generate_oval_sc_EntityItemBoolType(id, "generic_write"),
        "generic_execute", generate_oval_sc_EntityItemBoolType(id, "generic_execute"),
        "generic_all", generate_oval_sc_EntityItemBoolType(id, "generic_all"),
        NULL);
}
static oval_external_probe_value_map_t *generate_sid_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_domain", generate_oval_sc_EntityItemStringType(id, "trustee_domain"),
        NULL);
}
static oval_external_probe_value_map_t *generate_sid_sid_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "trustee_domain", generate_oval_sc_EntityItemStringType(id, "trustee_domain"),
        NULL);
}
static oval_external_probe_value_map_t *generate_systemmetric_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "index", generate_win_sc_EntityItemSystemMetricIndexType(id, "index"),
        "value", generate_oval_sc_EntityItemIntType(id, "value"),
        NULL);
}
static oval_external_probe_value_map_t *generate_uac_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "admin_approval_mode", generate_oval_sc_EntityItemBoolType(id, "admin_approval_mode"),
        "elevation_prompt_admin", generate_oval_sc_EntityItemStringType(id, "elevation_prompt_admin"),
        "elevation_prompt_standard", generate_oval_sc_EntityItemStringType(id, "elevation_prompt_standard"),
        "detect_installations", generate_oval_sc_EntityItemBoolType(id, "detect_installations"),
        "elevate_signed_executables", generate_oval_sc_EntityItemBoolType(id, "elevate_signed_executables"),
        "elevate_uiaccess", generate_oval_sc_EntityItemBoolType(id, "elevate_uiaccess"),
        "run_admins_aam", generate_oval_sc_EntityItemBoolType(id, "run_admins_aam"),
        "secure_desktop", generate_oval_sc_EntityItemBoolType(id, "secure_desktop"),
        "virtualize_write_failures", generate_oval_sc_EntityItemBoolType(id, "virtualize_write_failures"),
        NULL);
}
static oval_external_probe_value_map_t *generate_user_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "user", generate_oval_sc_EntityItemStringType(id, "user"),
        "enabled", generate_oval_sc_EntityItemBoolType(id, "enabled"),
        "group", generate_oval_sc_EntityItemStringType(id, "group"),
        "last_logon", generate_oval_sc_EntityItemIntType(id, "last_logon"),
        "full_name", generate_oval_sc_EntityItemStringType(id, "full_name"),
        "comment", generate_oval_sc_EntityItemStringType(id, "comment"),
        "password_age_days", generate_oval_sc_EntityItemIntType(id, "password_age_days"),
        "lockout", generate_oval_sc_EntityItemBoolType(id, "lockout"),
        "passwd_notreqd", generate_oval_sc_EntityItemBoolType(id, "passwd_notreqd"),
        "dont_expire_passwd", generate_oval_sc_EntityItemBoolType(id, "dont_expire_passwd"),
        "encrypted_text_password_allowed", generate_oval_sc_EntityItemBoolType(id, "encrypted_text_password_allowed"),
        "not_delegated", generate_oval_sc_EntityItemBoolType(id, "not_delegated"),
        "use_des_key_only", generate_oval_sc_EntityItemBoolType(id, "use_des_key_only"),
        "dont_require_preauth", generate_oval_sc_EntityItemBoolType(id, "dont_require_preauth"),
        "password_expired", generate_oval_sc_EntityItemBoolType(id, "password_expired"),
        "smartcard_required", generate_oval_sc_EntityItemBoolType(id, "smartcard_required"),
        "trusted_for_delegation", generate_oval_sc_EntityItemBoolType(id, "trusted_for_delegation"),
        "trusted_to_authenticate_for_delegation", generate_oval_sc_EntityItemBoolType(id, "trusted_to_authenticate_for_delegation"),
        NULL);
}
static oval_external_probe_value_map_t *generate_user_sid_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "user_sid", generate_oval_sc_EntityItemStringType(id, "user_sid"),
        "enabled", generate_oval_sc_EntityItemBoolType(id, "enabled"),
        "group_sid", generate_oval_sc_EntityItemStringType(id, "group_sid"),
        "last_logon", generate_oval_sc_EntityItemIntType(id, "last_logon"),
        NULL);
}
static oval_external_probe_value_map_t *generate_userright_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "userright", generate_win_sc_EntityItemUserRightType(id, "userright"),
        "trustee_name", generate_oval_sc_EntityItemStringType(id, "trustee_name"),
        "trustee_sid", generate_oval_sc_EntityItemStringType(id, "trustee_sid"),
        NULL);
}
static oval_external_probe_value_map_t *generate_volume_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "rootpath", generate_oval_sc_EntityItemStringType(id, "rootpath"),
        "file_system", generate_oval_sc_EntityItemStringType(id, "file_system"),
        "name", generate_oval_sc_EntityItemStringType(id, "name"),
        "drive_type", generate_win_sc_EntityItemDriveTypeType(id, "drive_type"),
        "volume_max_component_length", generate_oval_sc_EntityItemIntType(id, "volume_max_component_length"),
        "serial_number", generate_oval_sc_EntityItemIntType(id, "serial_number"),
        "file_case_sensitive_search", generate_oval_sc_EntityItemBoolType(id, "file_case_sensitive_search"),
        "file_case_preserved_names", generate_oval_sc_EntityItemBoolType(id, "file_case_preserved_names"),
        "file_unicode_on_disk", generate_oval_sc_EntityItemBoolType(id, "file_unicode_on_disk"),
        "file_persistent_acls", generate_oval_sc_EntityItemBoolType(id, "file_persistent_acls"),
        "file_file_compression", generate_oval_sc_EntityItemBoolType(id, "file_file_compression"),
        "file_volume_quotas", generate_oval_sc_EntityItemBoolType(id, "file_volume_quotas"),
        "file_supports_sparse_files", generate_oval_sc_EntityItemBoolType(id, "file_supports_sparse_files"),
        "file_supports_reparse_points", generate_oval_sc_EntityItemBoolType(id, "file_supports_reparse_points"),
        "file_supports_remote_storage", generate_oval_sc_EntityItemBoolType(id, "file_supports_remote_storage"),
        "file_volume_is_compressed", generate_oval_sc_EntityItemBoolType(id, "file_volume_is_compressed"),
        "file_supports_object_ids", generate_oval_sc_EntityItemBoolType(id, "file_supports_object_ids"),
        "file_supports_encryption", generate_oval_sc_EntityItemBoolType(id, "file_supports_encryption"),
        "file_named_streams", generate_oval_sc_EntityItemBoolType(id, "file_named_streams"),
        "file_read_only_volume", generate_oval_sc_EntityItemBoolType(id, "file_read_only_volume"),
        "file_sequential_write_once", generate_oval_sc_EntityItemBoolType(id, "file_sequential_write_once"),
        "file_supports_transactions", generate_oval_sc_EntityItemBoolType(id, "file_supports_transactions"),
        "file_supports_hard_links", generate_oval_sc_EntityItemBoolType(id, "file_supports_hard_links"),
        "file_supports_extended_attributes", generate_oval_sc_EntityItemBoolType(id, "file_supports_extended_attributes"),
        "file_supports_open_by_file_id", generate_oval_sc_EntityItemBoolType(id, "file_supports_open_by_file_id"),
        "file_supports_usn_journal", generate_oval_sc_EntityItemBoolType(id, "file_supports_usn_journal"),
        NULL);
}
static oval_external_probe_value_map_t *generate_wmi_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "namespace", generate_oval_sc_EntityItemStringType(id, "namespace"),
        "wql", generate_oval_sc_EntityItemStringType(id, "wql"),
        "result", generate_oval_sc_EntityItemStringType(id, "result"),
        NULL);
}
static oval_external_probe_value_map_t *generate_wmi57_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "namespace", generate_oval_sc_EntityItemStringType(id, "namespace"),
        "wql", generate_oval_sc_EntityItemStringType(id, "wql"),
        "result", generate_oval_sc_EntityItemStringType(id, "result"),
        NULL);
}
static oval_external_probe_value_map_t *generate_wuaupdatesearcher_datapoint(const char *id) {
    return oval_external_probe_value_map_new(
        "search_criteria", generate_oval_sc_EntityItemStringType(id, "search_criteria"),
        "update_id", generate_oval_sc_EntityItemStringType(id, "update_id"),
        NULL);
}
static datapoint_generator_t datapoint_generators[] = {
    {"accesstoken", generate_accesstoken_datapoint},
    {"activedirectory", generate_activedirectory_datapoint},
    {"activedirectory57", generate_activedirectory57_datapoint},
    {"auditeventpolicy", generate_auditeventpolicy_datapoint},
    {"auditeventpolicysubcategories", generate_auditeventpolicysubcategories_datapoint},
    {"cmdlet", generate_cmdlet_datapoint},
    {"dnscache", generate_dnscache_datapoint},
    {"file", generate_file_datapoint},
    {"fileauditedpermissions", generate_fileauditedpermissions_datapoint},
    {"fileeffectiverights", generate_fileeffectiverights_datapoint},
    {"group", generate_group_datapoint},
    {"group_sid", generate_group_sid_datapoint},
    {"interface", generate_interface_datapoint},
    {"junction", generate_junction_datapoint},
    {"license", generate_license_datapoint},
    {"lockoutpolicy", generate_lockoutpolicy_datapoint},
    {"metabase", generate_metabase_datapoint},
    {"ntuser", generate_ntuser_datapoint},
    {"passwordpolicy", generate_passwordpolicy_datapoint},
    {"peheader", generate_peheader_datapoint},
    {"port", generate_port_datapoint},
    {"printereffectiverights", generate_printereffectiverights_datapoint},
    {"process", generate_process_datapoint},
    {"registry", generate_registry_datapoint},
    {"regkeyauditedpermissions", generate_regkeyauditedpermissions_datapoint},
    {"regkeyeffectiverights", generate_regkeyeffectiverights_datapoint},
    {"service", generate_service_datapoint},
    {"serviceeffectiverights", generate_serviceeffectiverights_datapoint},
    {"sharedresource", generate_sharedresource_datapoint},
    {"sharedresourceauditedpermissions", generate_sharedresourceauditedpermissions_datapoint},
    {"sharedresourceeffectiverights", generate_sharedresourceeffectiverights_datapoint},
    {"sid", generate_sid_datapoint},
    {"sid_sid", generate_sid_sid_datapoint},
    {"systemmetric", generate_systemmetric_datapoint},
    {"uac", generate_uac_datapoint},
    {"user", generate_user_datapoint},
    {"user_sid", generate_user_sid_datapoint},
    {"userright", generate_userright_datapoint},
    {"volume", generate_volume_datapoint},
    {"wmi", generate_wmi_datapoint},
    {"wmi57", generate_wmi57_datapoint},
    {"wuaupdatesearcher", generate_wuaupdatesearcher_datapoint},
};
#define datapoint_generators_count 42

oval_external_probe_value_map_t *generate_windows_probe_datapoints(oval_subtype_t probe_type, const char *id) {
    const char *probe_type_str = oval_subtype_get_text(probe_type);
    if (probe_type_str == NULL) {
        return NULL;
    }

    int i;
    for (i=0; i<datapoint_generators_count; ++i) {
        if (strncmp(datapoint_generators[i].probe_type_str, probe_type_str, strlen(datapoint_generators[i].probe_type_str)) == 0)
            return datapoint_generators[i].gen_func(id);
    }
    return NULL;
}

#endif // EXTERNAL_PROBE_COLLECT

